apiVersion: v1
kind: Pod
metadata:
  name: basic-app
spec:
  containers:
  - name: basic-app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: ephemeral-storage
      mountPath: /data
  volumes:
  - name: ephemeral-storage
